---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-reports-scripts-configmap
data:
  getter.sh: |
    #!/bin/bash
    set -e

    mkdir -p /tmp/reports

    timestamp=$(date +%s)

    report_types=(
        'vulnerabilityreports'
        'configauditreport'
        'exposedsecretreport'
        'rbacassessmentreport'
        'infraassessmentreport'
        'clustercompliancereport'
        'clustervulnerabilityreport'
    )

    for report_type in "${report_types[@]}"; do
        output_file="/tmp/reports/${report_type}_${timestamp}.json"
        if kubectl get "$report_type" -o json > "$output_file"; then
            echo "Successfully wrote $output_file"
        else
            echo "Failed to get $report_type" >&2
        fi
    done
    
    touch /tmp/reports/report_done
    ls /tmp/reports