apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-reports-cronjob
spec:
  schedule: "0 23 * * *" # Every day at 23:00
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "trivy-operator"
          restartPolicy: OnFailure
          containers:
          - name: trivy-reports-getter
            image: bitnami/kubectl
            command: ["/bin/sh", "-c", "cp /scripts/getter.sh /tmp/getter.sh && chmod +x /tmp/getter.sh && /tmp/getter.sh"]
            volumeMounts:
            - name: scripts
              mountPath: "/scripts"
            - mountPath: "/etc/openstack"
              name: "cron-config"
              subPath: "openstack"
            - mountPath: "/tmp/reports"
              name: "reports"
          - name: "trivy-reports-uploader"
            image: "ghcr.io/gtema/openstack"
            command:
              - "/bin/sh"
              - "-c"
            args:
              - |
                timeout=60; \
                while [ ! -f /tmp/reports/report_done ] && [ $timeout -gt 0 ]; do \
                  sleep 1; \
                  timeout=$((timeout - 1)); \
                done; \
                if [ ! -f /tmp/reports/report_done ]; then \
                  echo "Error: report_done file not found after waiting."; \
                  exit 1; \
                fi; \
                cd /tmp/reports && \
                for file in *.json; do \
                  osc --os-cloud backup object-store object upload backup scan_results/${file} -vv; \
                done
            envFrom:
              - secretRef:
                  name: openstack-credentials
            volumeMounts:
              - mountPath: "/tmp/reports"
                name: "reports"
              - mountPath: "/etc/openstack"
                name: "cron-config"
                subPath: "openstack"

          
          volumes:
          - name: "scripts"
            configMap:
              name: trivy-reports-scripts-configmap
          - name: "cron-config"
            emptyDir:
              medium: "Memory"
          - name: "reports"
            emptyDir:
              medium: "Memory"
          - name: "kube-api-access"
            projected:
              defaultMode: 420
              sources:
                - serviceAccountToken:
                    expirationSeconds: 7200
                    path: "token"
                - configMap:
                    items:
                      - key: "ca.crt"
                        path: "ca.crt"
                    name: "kube-root-ca.crt"
                - downwardAPI:
                    items:
                      - fieldRef:
                          apiVersion: "v1"
                          fieldPath: "metadata.namespace"
                        path: "namespace"
          - name: "home-init"
            emptyDir:
              medium: "Memory"
          - name: "home-sidecar"
            emptyDir:
              medium: "Memory"